name: Build and Deploy Docs
on:
  push:
    branches:
      - master
      - v*
    tags-ignore:
      - v*
    paths:
      - .dumi/**
      - docs/**
      - src/**
      - .umirc.js
      - .github/**
      - README.md

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: pnpm install
      - name: Test
        run: pnpm test
      - name: Build package
        run: pnpm build
      - name: Build latest docs
        if: ${{github.ref == 'refs/heads/master'}}
        run: pnpm run doc
      - name: Deploy latest docs
        if: ${{github.ref == 'refs/heads/master'}}
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.ACCESS_TOKEN_WORKFLOW }}
          branch: gh-pages
          folder: site
          target-folder: latest
      - name: Build version docs
        if: ${{github.ref != 'refs/heads/master'}}
        run: pnpm doc-version
      - name: Deploy version docs
        if: ${{github.ref != 'refs/heads/master'}}
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.ACCESS_TOKEN_WORKFLOW }}
          branch: gh-pages
          folder: site
          target-folder: ${{github.ref}}
